#!/bin/bash

filename=$1

if [ $# -eq 0 ]; then
    echo "[-] Error: No arguments provided"
    exit 1
fi 

if [ -f $filename ]
then
    path_to_file=$(dirname "${filename}")
    base_filename=$(basename "${filename}")
    
    current_time=$(date "+%Y-%m-%d-%H-%M-%S")
    echo "Current Time : $current_time"

    new_filename=$path_to_file/$current_time-$base_filename
    echo "New Filename : " "$new_filename"

    cp $filename $new_filename
    exit 0
else
    echo "[-] Error: $filename does not exist"
    exit 1
fi
